using Microsoft.Extensions.Options;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SocksShoppingStore.Config;
using SocksShoppingStore.Models;

namespace SocksShoppingStore.Services
{
    public class PdfInvoiceService
    {
        private readonly FeatureFlags _features;

        public PdfInvoiceService(IOptions<FeatureFlags> features)
        {
            _features = features.Value;
            QuestPDF.Settings.License = LicenseType.Community;
        }

        public byte[] Generate(Order order)
        {
            var doc = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(30);
                    page.PageColor(Colors.White);

                    page.Header().Row(row =>
                    {
                        row.RelativeItem().Column(col =>
                        {
                            col.Item().Text("Invoice").FontSize(20).SemiBold();
                            col.Item().Text($"Order: {order.Id}");
                            col.Item().Text($"Date: {order.CreatedAt:yyyy-MM-dd HH:mm} UTC");
                        });
                    });

                    page.Content().Column(col =>
                    {
                        col.Spacing(10);
                        col.Item().Text("Billing To:").SemiBold();
                        col.Item().Text(order.CustomerName);
                        col.Item().Text(order.Email);
                        col.Item().Text($"{order.AddressLine1} {order.AddressLine2}");
                        col.Item().Text($"{order.City}, {order.PostalCode}, {order.Country}");

                        col.Item().LineHorizontal(0.5f);

                        col.Item().Table(table =>
                        {
                            table.ColumnsDefinition(columns =>
                            {
                                columns.RelativeColumn(6);
                                columns.RelativeColumn(2);
                                columns.RelativeColumn(2);
                            });

                            table.Header(header =>
                            {
                                header.Cell().Text("Item").SemiBold();
                                header.Cell().AlignRight().Text("Qty").SemiBold();
                                header.Cell().AlignRight().Text("Subtotal").SemiBold();
                            });

                            foreach (var it in order.Items)
                            {
                                table.Cell().Text(it.Name);
                                table.Cell().AlignRight().Text(it.Quantity.ToString());
                                table.Cell().AlignRight().Text(Helpers.Currency.Eur(it.Subtotal));
                            }
                        });

                        col.Item().LineHorizontal(0.5f);

                        col.Item().Column(cc =>
                        {
                            var t = order.Totals ?? new OrderTotals
                            {
                                SubtotalInclTax = order.Total,
                                SubtotalExTax = order.Total,
                                Discount = 0m,
                                Shipping = 0m,
                                TaxAmount = 0m,
                                TotalInclTax = order.Total,
                                TaxLabel = "VAT",
                                TaxRatePercent = 0m
                            };

                            cc.Item().AlignRight().Text($"Items: {Helpers.Currency.Eur(t.SubtotalInclTax)}");
                            if (t.Discount > 0m)
                                cc.Item().AlignRight().Text($"Discount: -{Helpers.Currency.Eur(t.Discount)}");
                            if (t.Shipping > 0m)
                                cc.Item().AlignRight().Text($"Shipping: {Helpers.Currency.Eur(t.Shipping)}");
                            cc.Item().AlignRight().Text($"{t.TaxLabel}: {Helpers.Currency.Eur(t.TaxAmount)} ({t.TaxRatePercent:0.##}%)");
                            cc.Item().AlignRight().Text($"Total: {Helpers.Currency.Eur(t.TotalInclTax)}").SemiBold();
                        });
                    });

                    page.Footer().AlignRight().Text("Generated by SocksShoppingStore (demo)").FontSize(10);
                });
            });

            return doc.GeneratePdf();
        }
    }
}

