name: .NET Build and Test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Даем воркфлоу права на запись в репозиторий для создания ветки gh-pages
permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build
        run: dotnet build SocksShoppingStore/SocksShoppingStore.sln --configuration Release

      - name: Grant Execute Permission to Selenium Manager
        run: chmod +x SocksShoppingStore.Tests/bin/Release/net8.0/selenium-manager/linux/selenium-manager

      - name: Start Web App
        env:
          ASPNETCORE_ENVIRONMENT: Production
        run: |
          dotnet run --project SocksShoppingStore/SocksShoppingStore.csproj --urls "http://0.0.0.0:5123" &
          sleep 15

      - name: Run Fast Tests (on dev branch)
        if: github.ref == 'refs/heads/dev'
        continue-on-error: true
        run: dotnet test SocksShoppingStore/SocksShoppingStore.sln --no-build --configuration Release --filter "TestCategory=Unit|TestCategory=Integration|TestCategory=API-Smoke|TestCategory=UI-Smoke"

      - name: Run Full Regression Tests (on PR to main)
        if: github.event_name == 'pull_request'
        continue-on-error: true
        run: dotnet test SocksShoppingStore/SocksShoppingStore.sln --no-build --configuration Release

      - name: Generate Allure Report (PRs only)
        if: github.event_name == 'pull_request'
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: SocksShoppingStore.Tests/bin/Release/net8.0/allure-results
          allure_report: allure-report
          gh_pages: gh-pages
          allure_history: allure-history

      - name: Upload Allure Report as Artifact (PRs only)
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Deploy Allure Report to GH Pages (on PR to main only)
        if: always() && github.event_name == 'pull_request'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          publish_branch: gh-pages
          keep_files: true
